duplocloud/tenant-terraform-generator

- README.md
- duplosdk/aws_emr.go
- main.go
- tf-generator/app/k8s-config.go
- tf-generator/app/k8s-secret.go
- tf-generator/aws-services/emr.go
- duplocloud_emr_cluster support added.
> duplocloud_emr_cluster support added.

- README.md
- duplosdk/aws_lambda_function.go
- duplosdk/utils.go
- main.go
> Readme updated.

- .envrc
> envrc updated.

- duplosdk/utils.go
- tf-generator/app/k8s-secret.go
- tf-generator/app/services.go
- tf-generator/aws-services/cloudfront.go
- tf-generator/aws-services/es.go
- tf-generator/aws-services/main.go
- tf-generator/aws-services/managed-airflow.go
- tf-generator/aws-services/redis.go
- Apache airflow resources wiring with s3 and KMS.
> Wiring of resources wherever possible in exported resources.

- README.md
- duplosdk/aws_cloudwatch.go
- main.go
- tf-generator/aws-services/cloudwatch-metrics.go
- tf-generator/aws-services/dynamodbv2.go
- Resource duplocloud_aws_cloudwatch_metric_alarm added.
> Resource duplocloud_aws_cloudwatch_metric_alarm added.

- README.md
- tf-generator/app/ecs.go
- tf-generator/app/k8s-config.go
- tf-generator/app/k8s-secret.go
- tf-generator/app/services.go
- tf-generator/aws-services/api-gateway-integration.go
- tf-generator/aws-services/asg.go
- tf-generator/aws-services/byoh.go
- tf-generator/aws-services/cloudfront.go
- tf-generator/aws-services/cloudwatch-event-rule.go
- tf-generator/aws-services/cloudwatch-metrics.go
- tf-generator/aws-services/dynamodbv2.go
- tf-generator/aws-services/ecr.go
- tf-generator/aws-services/emr.go
- tf-generator/aws-services/es.go
- tf-generator/aws-services/hosts.go
- tf-generator/aws-services/kafka.go
- tf-generator/aws-services/lambda-function.go
- tf-generator/aws-services/lb.go
- tf-generator/aws-services/managed-airflow.go
- tf-generator/aws-services/rds.go
- tf-generator/aws-services/redis.go
- tf-generator/aws-services/s3.go
- tf-generator/aws-services/sns.go
- tf-generator/aws-services/sqs.go
New resources duplocloud_aws_cloudwatch_event_rule and duplocloud_aws_cloudwatch_evduplocloud_aws_cloudwatch_event_target.
> duplocloud_aws_cloudwatch_event_rule and duplocloud_aws_cloudwatch_evduplocloud_aws_cloudwatch_event_target.

- README.md
- duplosdk/aws_target_group_attributes.go
- tf-generator/aws-services/lb.go
Resource `duplocloud_aws_target_group_attributes` is added.
> Resource `duplocloud_aws_target_group_attributes` is added.

- .envrc
- README.md
- main.go
- tf-generator/app/ecs.go
- tf-generator/app/k8s-config.go
- tf-generator/app/k8s-secret.go
- tf-generator/app/services.go
- tf-generator/aws-services/api-gateway-integration.go
- tf-generator/aws-services/asg.go
- tf-generator/aws-services/byoh.go
- tf-generator/aws-services/cloudfront.go
- tf-generator/aws-services/cloudwatch-event-rule.go
- tf-generator/aws-services/cloudwatch-metrics.go
- tf-generator/aws-services/dynamodbv2.go
- tf-generator/aws-services/ecr.go
- tf-generator/aws-services/emr.go
- tf-generator/aws-services/es.go
- tf-generator/aws-services/hosts.go
- tf-generator/aws-services/kafka.go
- tf-generator/aws-services/lambda-function.go
- tf-generator/aws-services/lb.go
- tf-generator/aws-services/managed-airflow.go
- tf-generator/aws-services/rds.go
- tf-generator/aws-services/redis.go
- tf-generator/aws-services/s3.go
- tf-generator/aws-services/sns.go
- tf-generator/aws-services/sqs.go
- tf-generator/aws-services/ssm-params.go
- tf-generator/common/utils.go
- tf-generator/tenant/tenant.go
- Feedback from Team after Engineering Call.
> Duplo 4737: Feedback from Team after Engineering Call.

- README.md
- main.go
- tf-generator/app/services.go
- tf-generator/aws-services/rds.go
- tf-generator/common/provider.go
- Random provider is used for rds password.
> Random provider is used for rds password.

- duplosdk/replication_controller.go
- main.go
- tf-generator/app/ecs.go
- tf-generator/app/services.go
- tf-generator/common/utils.go
> Bug fixes.

- README.md
- duplosdk/aws_lb_listener_rule.go
- duplosdk/types.go
- tf-generator/aws-services/lb.go
DUPLO-5354 - Add support of `duplocloud_aws_lb_listener_rule` resource..
> DUPLO-5354 - Add support of `duplocloud_aws_lb_listener_rule` resource..

- duplosdk/aws_batch.go
- go.mod
- go.sum
- tf-generator/app/main.go
- tf-generator/aws-services/batch-ce.go
- tf-generator/aws-services/batch-jd.go
- tf-generator/aws-services/batch-queue.go
- tf-generator/aws-services/batch-sp.go
- tf-generator/aws-services/main.go
- tf-generator/common/utils.go
- tf-generator/generator-registry.go
- vendor/github.com/ucarion/jcs/.gitignore
- vendor/github.com/ucarion/jcs/LICENSE
- vendor/github.com/ucarion/jcs/README.md
- vendor/github.com/ucarion/jcs/jcs.go
- vendor/modules.txt
- AWS batch resources are added.
> AWS batch resources are added.

- duplosdk/aws_timestream_database.go
- tf-generator/aws-services/timestream-db.go
- tf-generator/generator-registry.go
- Resources duplocloud_aws_timestreamwrite_database and duplocloud_aws_timestreamwrite_table added.
> Resources duplocloud_aws_timestreamwrite_database and duplocloud_aws_timestreamwrite_table added.

- duplosdk/ecache_instance.go
- tf-generator/aws-services/redis.go
- DUPLO-7984: Add TF Export Support for Memcache and Redis engine version.
> DUPLO-7984: Add TF Export Support for Memcache and Redis engine version.

- duplosdk/aws_lambda_function.go
- tf-generator/aws-services/lambda-function.go
Added support to export `image_configuration` ,`tracing_config` ,`ephemeral_storage` attributes for duplo_aws_lambda_function resource
> DUPLO 11666 TF Export support for `image_configuration`, `tracing_config` and `ephemeral_storage` for Lambda function

- tf-generator/aws-services/ssm-params.go
Removed env variable for secret store and replaced with response parameter
> DUPLO-13410 SSM Parameter palceholder support based on env var

- .envrc
- duplosdk/k8s_cron_job.go
- duplosdk/rds_instance.go
- tf-generator/app/k8s-cron_job.go
- tf-generator/aws-services/rds.go
added attribute support for storage type and IOPS in rds instance
> DUPLO-11580 support for RDS storage type and IOPS

- .envrc
- tf-generator/app/k8-cron-job.go
- tf-generator/app/k8-job.go
> Duplo 14355 k8 jobs

- .gitignore
- duplosdk/aws_dynamo_db.go
- tf-generator/aws-services/dynamodbv2.go
added   delete_protection, point in time recovery fields to export
___
enhancement
___
- Added support for deletion protection and point-in-time recovery in DynamoDB configurations.
- Updated the `DuploDynamoDBTableV2` struct to include new fields for managing deletion protection and recovery options.
- Enhanced the DynamoDB configuration generator to handle new attributes related to deletion protection and point-in-time recovery.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>aws_dynamo_db.go</strong><dd><code>Add Deletion Protection and Point-in-Time Recovery to DynamoDB Struct</code></dd></summary>
<hr>
duplosdk/aws_dynamo_db.go
<li>Added …
> DUPLO-15765: dynamodb - export delete_protection, point in time recovery

- scripts/apply.sh
- scripts/plan.sh
https://app.clickup.com/t/8655600/CUST-2271
Add line to clearly log project, tenant, and workspace.
___
enhancement
___
- Enhanced logging in `apply.sh` and `plan.sh` scripts to include tenant and workspace information.
- Modified echo statements to provide clearer logging of project, tenant, and workspace.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>apply.sh</strong><dd><code>Enhance logging with tenant and workspace details</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
scripts/apply.sh
<li>Enhanced logging to include tenant and workspace information.<br> <li> Modified the echo statement to display project, tenant, and …
> CUST-2271: Merge back small logging change form USM scripts

- .envrc
- duplosdk/rds_instance.go
- scripts/import.sh
- tf-generator/aws-services/rds.go
> DUPLO-20877 DUPLO-20528 support for performance insight and fix for missing schema attribute for serverless cluster

- .envrc
- tf-generator/aws-services/rds.go
Fixed duplicate variable issue in rds, and removed unwnated attributes in read replica
> DUPLO-20528 Rds bug fix

- tf-generator/aws-services/lambda-function.go
Added variable to pass s3 bucket and s3 key to lambda if package type is zip
> Duplo 20469 Bug Fix Lambda function

- tf-generator/app/k8s-config.go
Added interpolation fix for config mao
> Duplo-26851 [Techstyle] TF generator error on export

- duplosdk/rds_instance.go
- duplosdk/tenant.go
- tf-generator/aws-services/rds.go
Added enhanced_monitoring field to rds resource
> DUPLO-29491 TF Exporter: Add enhanced monitoring field support to RDS read replica 
